/*
** EPITECH PROJECT, 2019
** OOP_arcade_2018
** File description:
** PacmanSprites
*/

#ifndef PACMANSPRITES_HPP_
#define PACMANSPRITES_HPP_

#include "Object.hpp"

static Sprite none {{}};

static Sprite mapSprite
{
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},    
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},    
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
};

static Sprite blackSquare = {
    {BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK},
};

static Sprite pacGum = {
    {NONE, NONE, NONE},
    {NONE, WHITE, NONE},
    {NONE, NONE, NONE},
};

static SpriteSheet bigPacGum = {
    {
        {NONE, NONE, NONE},
        {NONE, RED, NONE},
        {NONE, NONE, NONE},
    },
    {
        {NONE, NONE, NONE},
        {NONE, WHITE, NONE},
        {NONE, NONE, NONE},
    },
};

static Sprite redGhost = {
    {WHITE, RED, WHITE},
    {RED, RED, RED},
    {RED, NONE, RED},
};

static Sprite cyanGhost = {
    {WHITE, CYAN, WHITE},
    {CYAN, CYAN, CYAN},
    {CYAN, NONE, CYAN},
};

static Sprite magentaGhost = {
    {WHITE, MAGENTA, WHITE},
    {MAGENTA, MAGENTA, MAGENTA},
    {MAGENTA, NONE, MAGENTA},
};

static Sprite yellowGhost = {
    {WHITE, YELLOW, WHITE},
    {YELLOW, YELLOW, YELLOW},
    {YELLOW, NONE, YELLOW},
};

static SpriteSheet animatedGate = {
    {
        {BLUE, BLUE, BLUE},
        {BLUE, BLUE, BLUE},
        {BLUE, BLUE, BLUE},
    },
    {
        {YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW},
    },
    {
        {WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE},
    },
};

static Sprite normalGate = {
    {BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE},  
};

static SpriteSheet LeftBigPacMan = {
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
};

static SpriteSheet RightBigPacMan = {
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
};

#endif /* !PACMANSPRITES_HPP_ */
