/*
** EPITECH PROJECT, 2019
** snake
** File description:
** SnakeScene
*/

#include "PacmanScene.hpp"

static Sprite none {{}};

static Sprite mapSprite
{
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},    
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},    
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
};

static Sprite blackSquare = {
    {BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK},
};

static Sprite pacGum = {
    {NONE, NONE, NONE},
    {NONE, WHITE, NONE},
    {NONE, NONE, NONE},
};

static SpriteSheet bigPacGum = {
    {
        {NONE, NONE, NONE},
        {NONE, RED, NONE},
        {NONE, NONE, NONE},
    },
    {
        {NONE, NONE, NONE},
        {NONE, WHITE, NONE},
        {NONE, NONE, NONE},
    },
};

static Sprite redGhost = {
    {WHITE, RED, WHITE},
    {RED, RED, RED},
    {RED, NONE, RED},
};

static Sprite cyanGhost = {
    {WHITE, CYAN, WHITE},
    {CYAN, CYAN, CYAN},
    {CYAN, NONE, CYAN},
};

static Sprite magentaGhost = {
    {WHITE, MAGENTA, WHITE},
    {MAGENTA, MAGENTA, MAGENTA},
    {MAGENTA, NONE, MAGENTA},
};

static Sprite yellowGhost = {
    {WHITE, YELLOW, WHITE},
    {YELLOW, YELLOW, YELLOW},
    {YELLOW, NONE, YELLOW},
};

static SpriteSheet animatedGate = {
    {
        {BLUE, BLUE, BLUE},
        {BLUE, BLUE, BLUE},
        {BLUE, BLUE, BLUE},
    },
    {
        {YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW},
    },
    {
        {WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE},
    },
};

static Sprite normalGate = {
    {BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE},  
};

static SpriteSheet LeftBigPacMan = {
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
};

static SpriteSheet RightBigPacMan = {
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
    {
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW},
        {NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE},
        {NONE, NONE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, NONE, NONE},
    },
};

PacmanScene::PacmanScene()
: Scene("PacmanScene", none)
{
    Object *rightPacMan = this->addObject("PacmanRight", RightBigPacMan, {81, 27});
    Object *leftPacMan = this->addObject("PacmanLeft", LeftBigPacMan, {10, 27});
    
    this->addObject(new Text("PacmanTitle", "PacMan", 100, YELLOW, none, {37, 6}));
    this->addObject(new Text("Info", "Press Enter to Start", 70, WHITE, none, {24, 27}));
    rightPacMan->getAnimation().setLoop(true);
    rightPacMan->getAnimation().setAnimationSpeed(0.1);
    leftPacMan->getAnimation().setLoop(true);
    leftPacMan->getAnimation().setAnimationSpeed(0.1);
}

PacmanScene::~PacmanScene()
{
}

static void initGum(Object *gum)
{
    gum->getMovement().setBlocking(false);
    gum->getAnimation().setAnimationSpeed(0.2);
    gum->getAnimation().setLoop(true);
}

void PacmanScene::initPacGums(void)
{
    Object *gum1 = this->addObject("BigAPacGum1", bigPacGum, {2 * 3, 2 * 3});
    Object *gum2 = this->addObject("BigAPacGum2", bigPacGum, {18 * 3, 2 * 3});
    Object *gum3 = this->addObject("BigAPacGum3", bigPacGum, {5 * 3, 15 * 3});
    Object *gum4 = this->addObject("BigAPacGum4", bigPacGum, {15 * 3, 15 * 3});

    for (int j = 0; j < 19 * 3; j++) {
        for (int i = 0; i < 20 * 3; i++) {
            if ((j == 21 || j == 27 || j == 33)     // Gums out of the area
            && (i < 15 || i > 45))
                continue;
            if (((j == 9 * 3 || j == 10 * 3)        // Box in the Middle
            && i > 8 * 3 && i < 12 * 3)
            || (i == 10 * 3 && j == 8 * 3))
                continue;
            if ((i == 2 * 3 && j == 2 * 3)          // BigPacGums
            || (i == 18 * 3 && j == 2 * 3)
            || (i == 5 * 3 && j == 15 * 3)
            || (i == 15 * 3 && j == 15 * 3))
                continue;
            if (mapSprite[j][i] == NONE && i > 3 && i < 19 * 3
            && i % 3 == 0 && j % 3 == 0)
                this->addObject("APacGum" + std::to_string(i) + std::to_string(j), pacGum, {i, j})->getMovement().setBlocking(false);
        }
    }
    initGum(gum1);
    initGum(gum2);
    initGum(gum3);
    initGum(gum4);
}

void PacmanScene::initGhosts()
{
    this->addObject(new Ghost("GhostRed", redGhost, this, {9 * 3, 9 * 3}));
    this->addObject(new Ghost("GhostYellow", yellowGhost, this, {10 * 3, 9 * 3}));
    this->addObject(new Ghost("GhostCyan", cyanGhost, this, {11 * 3, 9 * 3}));
    this->addObject(new Ghost("GhostMagenta", magentaGhost, this, {10 * 3, 10 * 3}));
}

void PacmanScene::initGame()
{
    this->removeAllObjects();
    this->addObject(new Pacman(this));
    this->addObject("PacmanMap", mapSprite)->getMovement().setBlocking(true);
    this->addObject(new Teleporter("Teleporter1", blackSquare, {61, 27}, {-3, 27}));
    this->addObject(new Teleporter("Teleporter2", blackSquare, {-1, 27}, {63, 27})); 
    initPacGums();
    initGhosts();
    this->addObject(new Text("Score", "Score: " + std::to_string(_score), 40, WHITE, none, {22 * 3, 3 * 3}));
    this->addObject("Gate", normalGate, {10 * 3, 8 * 3})->getMovement().setBlocking(true);
    _gateSecondsRemaining = 5;
}

void PacmanScene::manageEvents(std::map<Input, bool> &inputs)
{
    if (!_startMenu && !_endMenu)
        objects["Pacman"]->manageEvents(inputs);
    if (_startMenu) {
        if (inputs[RETURN_KEY]) {
            _startMenu = false;
            initGame();
        }
    }
}

void PacmanScene::affraidGhosts()
{
    for (auto &i : this->objects) {
        if (i.first.find("Ghost", 0) != std::string::npos) {
            ((Ghost *)i.second)->affraid();
        }
    }
}

void PacmanScene::unaffraidGhosts()
{
    for (auto &i : this->objects) {
        if (i.first.find("Ghost", 0) != std::string::npos
        && ((Ghost *)i.second)->isAlive()) {
            ((Ghost *)i.second)->unaffraid();
        }
    }
}

static bool collide(std::pair<int, int> pos1, std::pair<int, int> size1,
    std::pair<int, int> pos2, std::pair<int, int> size2)
{
    return pos1.first < pos2.first + size2.first
    && pos1.first + size1.first > pos2.first
    && pos1.second < pos2.second + size2.second
    && pos1.second + size1.second > pos2.second;
}

bool PacmanScene::ghostsInBox()
{
    std::pair<int, int> pos;

    for (auto &i : this->objects) {
        if (i.second)
            pos = (std::pair<int, int>)i.second->getMovement().getPosition();
        else
            continue;
        if (i.first.find("Ghost", 0) != std::string::npos
        && (collide(pos, {3, 3}, {9 * 3, 9 * 3}, {9, 6})
        || collide(pos, {3, 3}, {10 * 3, 8 * 3}, {3, 3}))) {
            return true;
        }
    }
    return false;
}

float PacmanScene::update(IDisplayModule *displays)
{
    float delta = Scene::update(displays);

    if (_startMenu)
        return delta;
    if (_needToClose == true && !ghostsInBox()) {
        this->addObject("Gate", normalGate, {10 * 3, 8 * 3})->getMovement().setBlocking(true);
        _needToClose = false;
        _needToOpen = false;
    }
    if (getObject("Gate") && _needToOpen) {
        _gateSecondsRemaining -= delta;
        if (_gateSecondsRemaining <= 0) {
            _needToOpen = false;
            _needToClose = true;
            removeObject("Gate");
        } else if (_gateSecondsRemaining <= 2 && !getObject("Gate")->getAnimation().isAnimated()) {
            getObject("Gate")->getAnimation().changeSpriteSheet(animatedGate);
            getObject("Gate")->getAnimation().setAnimationSpeed(0.1);
            getObject("Gate")->getAnimation().setLoop(true);
        }
    }
    ((Text *)getObject("Score"))->setText("Score: " + std::to_string(_score));
    return delta;
}