/*
** EPITECH PROJECT, 2019
** snake
** File description:
** SnakeScene
*/

#include "PacmanScene.hpp"

static Sprite none {{}};

static Sprite mapSprite
{
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},    
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},    
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
    {NONE, NONE, NONE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, NONE, NONE, NONE},
};

static Sprite blackSquare = {
    {BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK},
};

static Sprite pacGum = {
    {NONE, NONE, NONE},
    {NONE, WHITE, NONE},
    {NONE, NONE, NONE},
};

static SpriteSheet bigPacGum = {
    {
        {NONE, NONE, NONE},
        {NONE, RED, NONE},
        {NONE, NONE, NONE},
    },
    {
        {NONE, NONE, NONE},
        {NONE, WHITE, NONE},
        {NONE, NONE, NONE},
    },
};

static Sprite redGhost = {
    {WHITE, RED, WHITE},
    {RED, RED, RED},
    {RED, NONE, RED},
};

static Sprite cyanGhost = {
    {WHITE, CYAN, WHITE},
    {CYAN, CYAN, CYAN},
    {CYAN, NONE, CYAN},
};

static Sprite magentaGhost = {
    {WHITE, MAGENTA, WHITE},
    {MAGENTA, MAGENTA, MAGENTA},
    {MAGENTA, NONE, MAGENTA},
};

static Sprite yellowGhost = {
    {WHITE, YELLOW, WHITE},
    {YELLOW, YELLOW, YELLOW},
    {YELLOW, NONE, YELLOW},
};

static SpriteSheet animatedGate = {
    {
        {BLUE, BLUE, BLUE},
        {BLUE, BLUE, BLUE},
        {BLUE, BLUE, BLUE},
    },
    {
        {YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW},
        {YELLOW, YELLOW, YELLOW},
    },
    {
        {WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE},
    },
};

static Sprite normalGate = {
    {BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE},
    {BLUE, BLUE, BLUE},  
};

static void initGum(Object *gum)
{
    gum->getMovement().setBlocking(true);
    gum->getAnimation().setAnimationSpeed(0.2);
    gum->getAnimation().setLoop(true);
}

void PacmanScene::initPacGums(void)
{
    Object *gum1 = this->addObject("BigPacGum1", bigPacGum, {2 * 3, 2 * 3});
    Object *gum2 = this->addObject("BigPacGum2", bigPacGum, {18 * 3, 2 * 3});
    Object *gum3 = this->addObject("BigPacGum3", bigPacGum, {5 * 3, 15 * 3});
    Object *gum4 = this->addObject("BigPacGum4", bigPacGum, {15 * 3, 15 * 3});

    for (int j = 0; j < 19 * 3; j++) {
        for (int i = 0; i < 20 * 3; i++) {
            if ((j == 21 || j == 27 || j == 33)     // Gums out of the area
            && (i < 15 || i > 45))
                continue;
            if (((j == 9 * 3 || j == 10 * 3)        // Box in the Middle
            && i > 8 * 3 && i < 12 * 3)
            || (i == 10 * 3 && j == 8 * 3))
                continue;
            if ((i == 2 * 3 && j == 2 * 3)          // BigPacGums
            || (i == 18 * 3 && j == 2 * 3)
            || (i == 5 * 3 && j == 15 * 3)
            || (i == 15 * 3 && j == 15 * 3))
                continue;
            if (mapSprite[j][i] == NONE && i > 3 && i < 19 * 3
            && i % 3 == 0 && j % 3 == 0)
                this->addObject("PacGum" + std::to_string(i) + std::to_string(j), pacGum, {i, j})->getMovement().setBlocking(true);
        }
    }
    initGum(gum1);
    initGum(gum2);
    initGum(gum3);
    initGum(gum4);
}

PacmanScene::PacmanScene()
: Scene("PacmanScene", none)
{
    this->addObject(new Pacman(this));
    this->addObject("PacmanMap", mapSprite)->getMovement().setBlocking(true);
    this->addObject(new Teleporter("Teleporter1", blackSquare, {61, 27}, {-3, 27}));
    this->addObject(new Teleporter("Teleporter2", blackSquare, {-1, 27}, {63, 27})); 
    initPacGums();
    this->addObject(new Ghost("GhostRed", redGhost, this, {9 * 3, 9 * 3}));
    this->addObject(new Ghost("GhostYellow", yellowGhost, this, {10 * 3, 9 * 3}));
    this->addObject(new Ghost("GhostCyan", cyanGhost, this, {11 * 3, 9 * 3}));
    this->addObject(new Ghost("GhostMagenta", magentaGhost, this, {10 * 3, 10 * 3}));
}

PacmanScene::~PacmanScene()
{
}

void PacmanScene::manageEvents(std::map<Input, bool> &inputs)
{
    objects["Pacman"]->manageEvents(inputs);
}